import { z } from "zod";

const identifierBase = z
  .object({
    email: z.string().trim().toLowerCase().email().optional(),
    mobile: z.string().trim().optional(),
  })
  .refine((data) => Boolean(data.email || data.mobile), {
    message: "Provide an email or a mobile number",
    path: ["email"],
  });

// `pno` (UPP departmental ID) is captured at signup — it is the User primary key
// (architecture.md Design Decision D1) and is externally issued, so it cannot be
// generated by this system; the officer supplies their own.
const signupCore = {
  pno: z.string().trim().min(3, "PNO must be at least 3 characters").max(32),
  name: z.string().trim().min(2, "Name must be at least 2 characters").max(120),
};

export const signupRequestOtpSchema = z.object(signupCore).and(identifierBase);

export const signupVerifySchema = z.object({
  ...signupCore,
  email: z.string().trim().toLowerCase().email().optional(),
  mobile: z.string().trim().optional(),
  code: z.string().regex(/^\d{6}$/, "OTP must be a 6-digit code"),
});

export const signinRequestOtpSchema = identifierBase;

export const signinVerifySchema = z.object({
  email: z.string().trim().toLowerCase().email().optional(),
  mobile: z.string().trim().optional(),
  code: z.string().regex(/^\d{6}$/, "OTP must be a 6-digit code"),
});

// ── Password auth ──────────────────────────────────────────────────────────

/** Either half of what an officer already knows: their PNO or registered email. */
const passwordIdentifier = z.string().trim().min(3, "Enter your PNO or email").max(254);

/** Officers sign in with their PNO or email, plus their password. */
export const signinPasswordSchema = z.object({
  identifier: passwordIdentifier,
  password: z.string().min(1, "Enter your password").max(128),
});

const newPassword = z
  .string()
  .min(8, "Password must be at least 8 characters")
  .max(128, "Password must be at most 128 characters");

export const changePasswordSchema = z
  .object({
    currentPassword: z.string().min(1, "Enter your current password").max(128),
    newPassword,
  })
  .refine((data) => data.currentPassword !== data.newPassword, {
    message: "The new password must be different from the current one",
    path: ["newPassword"],
  });

/** "Forgot password?" from the sign-in screen — same shape plus the identifier. */
export const resetPasswordSchema = z
  .object({
    identifier: passwordIdentifier,
    currentPassword: z.string().min(1, "Enter your current password").max(128),
    newPassword,
  })
  .refine((data) => data.currentPassword !== data.newPassword, {
    message: "The new password must be different from the current one",
    path: ["newPassword"],
  });

export type SigninPasswordInput = z.infer<typeof signinPasswordSchema>;
export type ChangePasswordInput = z.infer<typeof changePasswordSchema>;
export type ResetPasswordInput = z.infer<typeof resetPasswordSchema>;

export type SignupRequestOtpInput = z.infer<typeof signupRequestOtpSchema>;
export type SignupVerifyInput = z.infer<typeof signupVerifySchema>;
export type SigninRequestOtpInput = z.infer<typeof signinRequestOtpSchema>;
export type SigninVerifyInput = z.infer<typeof signinVerifySchema>;
