import { z } from "zod";

const identifierBase = z
  .object({
    email: z.string().trim().toLowerCase().email().optional(),
    mobile: z.string().trim().optional(),
  })
  .refine((data) => Boolean(data.email || data.mobile), {
    message: "Provide an email or a mobile number",
    path: ["email"],
  });

// `pno` (UPP departmental ID) is captured at signup — it is the User primary key
// (architecture.md Design Decision D1) and is externally issued, so it cannot be
// generated by this system; the officer supplies their own.
const signupCore = {
  pno: z.string().trim().min(3, "PNO must be at least 3 characters").max(32),
  name: z.string().trim().min(2, "Name must be at least 2 characters").max(120),
};

export const signupRequestOtpSchema = z.object(signupCore).and(identifierBase);

export const signupVerifySchema = z.object({
  ...signupCore,
  email: z.string().trim().toLowerCase().email().optional(),
  mobile: z.string().trim().optional(),
  code: z.string().regex(/^\d{6}$/, "OTP must be a 6-digit code"),
});

export const signinRequestOtpSchema = identifierBase;

export const signinVerifySchema = z.object({
  email: z.string().trim().toLowerCase().email().optional(),
  mobile: z.string().trim().optional(),
  code: z.string().regex(/^\d{6}$/, "OTP must be a 6-digit code"),
});

export type SignupRequestOtpInput = z.infer<typeof signupRequestOtpSchema>;
export type SignupVerifyInput = z.infer<typeof signupVerifySchema>;
export type SigninRequestOtpInput = z.infer<typeof signinRequestOtpSchema>;
export type SigninVerifyInput = z.infer<typeof signinVerifySchema>;
